package net.protocol;

public enum CommandType {
	CHECK_UPDATE, LOGIN, ALL_PATIENTS, ALL_CONSULTATIONS, GET_CONSULTATIONS_BY_DOCTOR_AND_PATIENT, UPDATE_CONSULTATION, ADD_NEW_PATIENT, GET_CONSULTATION_BY_PATIENT, UPDATE_PATIENT, GET_DOCTOR_BY_NAME, GET_AVAILABLE_DOCTORS, CREATE_CONSULTATION, DELETE_CONSULTATION, GET_PATIENTS_BY_DOCTOR ,FINISH
}
